export const canvasStrings = {
    nodeActionsLabel: 'Node actions',
    generating: 'Generating...',
    clearCanvas: 'Clear all nodes',
    clearConfirm: 'Are you sure you want to clear all nodes?',
    clearConfirmTitle: 'Clear Canvas',
    clearConfirmButton: 'Clear all',
    imageUploading: 'Uploading image...',
    imageUploadFailed: 'Image upload failed. Please try again.',
    imageReadFailed: 'Failed to read image file.',
    imageUnsafeUrl: 'Image URL failed security validation.',
    imageFileTooLarge: 'Image exceeds 5 MB size limit.',
    imageUnsupportedType: 'Unsupported image format. Use JPEG, PNG, GIF, or WebP.',
    docUploading: 'Uploading document...',
    docUploadFailed: 'Document upload failed. Please try again.',
    docReadFailed: 'Failed to read document file.',
    docFileTooLarge: 'Document exceeds 15 MB size limit.',
    docUnsupportedType: 'Unsupported format. Use PDF, TXT, or CSV.',
    docMagicByteMismatch: 'File contents do not match declared type.',
    docParsingFailed: 'Failed to extract text from document.',
    docAiReady: 'AI Ready',
    docAiReadyTooltip: 'Document text extracted — available for AI generation',
    docProcessing: 'Processing document...',
    docDownload: 'Download',
    docOpenNewTab: 'Open in new tab',
    docRemove: 'Remove attachment',
    docFormatNotSupported: 'This format is not yet supported. Use PDF, TXT, or CSV.',
    docAuthUnavailable: 'Authentication or workspace context unavailable.',
    docReadHeaderFailed: 'Failed to read file header.',
    zoomControls: {
        zoomIn: 'Zoom In',
        zoomOut: 'Zoom Out',

        lockCanvas: 'Lock Canvas',
        unlockCanvas: 'Unlock Canvas',
        radarLabel: 'Canvas radar — click to fit all nodes',
    },
    resize: {
        resizeNode: 'Resize node',
        resizeHandle: 'Drag to resize',
        corner: 'Corner resize handle',
        edge: 'Edge resize handle',
        expandWidth: 'Expand width',
        expandHeight: 'Expand height',
        reduceWidth: 'Reduce width',
        reduceHeight: 'Reduce height',
    },
};
