export const canvasStrings = {
    addNode: 'Add node',
    promptPlaceholder: 'Type a prompt (e.g. Create a LinkedIn post about discipline)',
    generating: 'Generating...',
    regenerate: 'Regenerate',
    delete: 'Delete',
    edit: 'Edit',
    generatedBy: 'Generated by Gemini',
    synthesize: 'Generate combined idea',
    clearCanvas: 'Clear all nodes',
    clearConfirm: 'Are you sure you want to clear all nodes?',
    clearConfirmTitle: 'Clear Canvas',
    clearConfirmButton: 'Clear all',
};
