/**
 * Knowledge Bank String Resources
 * Extracted from main strings.ts to respect 300-line file limit
 */
export const knowledgeBankStrings = {
    title: 'Knowledge Bank',
    addButton: 'Add to Knowledge Bank',
    uploadFile: 'Upload File',
    pasteText: 'Add Text',
    viewBank: 'View Knowledge Bank',
    saveEntry: 'Save to Knowledge Bank',
    toggleEntry: 'Toggle entry enabled',
    editEntry: 'Edit entry',
    deleteEntry: 'Delete entry',
    deleteConfirm: 'Delete?',
    toggleEnable: 'Enable',
    toggleDisable: 'Disable',
    pinEntry: 'Pin to always include in AI context',
    unpinEntry: 'Unpin entry',
    pinnedBadge: 'Pinned',
    emptyState: 'No entries yet',
    emptyStateDescription: 'Add text, images, PDFs, or Word documents to your Knowledge Bank. All AI-generated nodes will use this context automatically.',
    addFirstEntry: 'Add First Entry',
    maxEntriesReached: 'Limit reached',
    maxEntriesDescription: 'Delete a document to add more (25 max)',
    entryCount: 'entries',
    documentCount: 'documents',
    characterCount: 'characters',
    titlePlaceholder: 'Entry title',
    contentPlaceholder: 'Paste your text here...',
    processingImage: 'Processing image...',
    compressingImage: 'Compressing image...',
    describingImage: 'Describing image with AI...',
    imageDescribed: 'AI-generated description added for image',
    imageDescriptionFallback: 'Image uploaded (AI description unavailable)',
    imageDescriptionPrompt: 'Describe this image in detail for use as reference context in a knowledge base. Focus on key visual elements, text content if any, diagrams, charts, or notable features. Be concise but comprehensive.',
    processingDocx: 'Extracting text from Word document...',
    processingPdf: 'Extracting text from PDF...',
    pdfScannedFallback: 'Scanned PDF detected — switching to AI-powered reading...',
    pdfExtractionPrompt: 'Extract all text from this PDF document exactly as it appears. Output only the extracted text content, preserving paragraph structure and line breaks. Do not add commentary, headers, or formatting beyond what exists in the original document.',
    chunkingDocument: 'Splitting large document into sections...',
    pdfExtracted: 'PDF content extracted',
    documentChunkTitle: 'Part',
    chunkBadge: 'chunk',
    documentGroup: {
        partsCount: 'parts',
        expand: 'Show parts',
        collapse: 'Hide parts',
        toggleAll: 'Toggle all parts',
        deleteDocument: 'Delete document',
        deleteDocumentConfirm: 'Delete this document and all its parts?',
    },
    summarizing: 'Generating summary...',
    summarized: 'Summary generated',
    documentSummarizing: 'Generating document summary...',
    documentSummarized: 'Document summary generated',
    documentSummaryPrompt: 'You are given the full text of a single document, split across multiple sections. Synthesize them into a cohesive 4-6 sentence summary that captures all major themes, key arguments, and important details. Preserve important specifics, names, and data points. Be factual and concise.',
    summaryPromptBrief: 'Summarize the following text in 1 concise sentence for use as reference context. Capture only the single most important point.',
    summaryPromptStandard: 'Summarize the following text in 2-3 concise sentences for use as reference context in a knowledge base. Capture the key points, main ideas, and any critical details. Be factual and concise.',
    summaryPromptDetailed: 'Provide a detailed summary (4-6 sentences) of the following text for use as reference context in a knowledge base. Cover all major themes, supporting details, and conclusions. Preserve important specifics, names, and data points.',
    summaryLabel: 'Summary',
    tags: {
        label: 'Tags',
        placeholder: 'Add tag...',
        addTag: 'Add tag',
        removeTag: 'Remove tag',
        maxReached: 'Maximum of 5 tags reached',
        tooLong: 'Tag must be 30 characters or less',
        duplicate: 'Tag already exists',
        filterByTag: 'Filter by tag',
        clearFilter: 'Clear tag filter',
        noTags: 'No tags',
    },
    search: {
        placeholder: 'Search entries...',
        noResults: 'No matching entries',
        filterAll: 'All',
        filterText: 'Text',
        filterImage: 'Image',
        filterDocument: 'Document',
    },
    ai: {
        kbUsageGuidance: 'Use the following Knowledge Bank reference material to ground your response in accurate, workspace-specific context. Prioritize Knowledge Bank facts over general knowledge when they are relevant to the request.',
        kbTransformGuidance: 'Reference the following Knowledge Bank material to maintain factual accuracy and consistency during transformation.',
        kbWrapperStart: '--- Workspace Knowledge Bank ---',
        kbWrapperEnd: '--- End Knowledge Bank ---',
        catalogHeader: '=== DOCUMENT CATALOG ===',
        docSummariesHeader: '=== DOCUMENT SUMMARIES ===',
        chapterSummariesHeader: '=== CHAPTER SUMMARIES ===',
        rawContentHeader: '=== RAW CONTENT ===',
    },
    errors: {
        fileTooLarge: 'File exceeds 10MB limit',
        unsupportedType: 'Unsupported file type. Supported: TXT, MD, JSON, PNG, JPG, PDF, DOCX',
        uploadFailed: 'Failed to upload file',
        saveFailed: 'Failed to save entry',
        loadFailed: 'Failed to load Knowledge Bank',
        deleteFailed: 'Failed to delete entry',
        maxEntries: 'Maximum of 25 documents reached',
        contentTooLarge: 'Content exceeds 10,000 character limit',
        titleRequired: 'Title is required',
        pdfParseFailed: 'Failed to extract text from PDF',
        pdfEmpty: 'PDF contains no extractable text',
        docxParseFailed: 'Failed to extract text from Word document',
        docxEmpty: 'Word document contains no extractable text',
        imageDescriptionFailed: 'AI image description failed, using fallback',
        summarizationFailed: 'Summary generation failed',
    },
} as const;
