export const settingsStrings = {
    title: 'Settings',
    appearance: 'Appearance',
    canvas: 'Canvas',
    account: 'Account',
    keyboard: 'Keyboard Shortcuts',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    themeSepia: 'Sepia',
    themeGrey: 'Grey',
    themeDarkBlack: 'Dark Black',
    canvasGrid: 'Show grid',
    autoSave: 'Auto-save',
    autoSaveInterval: 'Auto-save interval',
    seconds: 'seconds',
    compactMode: 'Compact mode',
    canvasScrollMode: 'Scroll behavior',
    canvasScrollZoom: 'Canvas Zoom',
    canvasScrollNavigate: 'Canvas Navigation',
    connectorStyle: 'Connector style',
    connectorSolid: 'Solid',
    connectorSubtle: 'Subtle',
    connectorThick: 'Thick',
    connectorDashed: 'Dashed',
    connectorDotted: 'Dotted',
    freeFlow: 'Free flow mode',
    close: 'Close',
    toolbar: 'Toolbar',
    toolbarLayout: 'Toolbar Layout',
    toolbarBar1: 'Bar 1 (Quick Actions)',
    toolbarBar2: 'Bar 2 (More Actions)',
    toolbarMoveToBar1: 'Move to Bar 1',
    toolbarMoveToBar2: 'Move to Bar 2',
    toolbarReset: 'Reset to Default',
    toolbarMinWarning: 'Each bar must have at least 2 actions',
};
