/**
 * String Resources - Single Source of Truth for all UI text
 * NO hardcoded strings allowed in components
 */
export const strings = {
    app: {
        name: 'ActionStation',
        tagline: 'Think visually. Connect ideas.',
    },
    auth: {
        signInWithGoogle: 'Sign in with Google',
        signOut: 'Sign out',
        signingIn: 'Signing in...',
        welcome: 'Welcome back',
    },
    workspace: {
        newWorkspace: 'New Workspace',
        untitled: 'Untitled Workspace',
        created: 'Workspace created',
        deleteConfirm: 'Are you sure you want to delete this workspace?',
    },
    canvas: {
        addNode: 'Add node',
        promptPlaceholder: 'Type a prompt (e.g. Create a LinkedIn post about discipline)',
        generating: 'Generating...',
        regenerate: 'Regenerate',
        delete: 'Delete',
        edit: 'Edit',
        generatedBy: 'Generated by Gemini',
        synthesize: 'Generate combined idea',
        clearCanvas: 'Clear all nodes',
        clearConfirm: 'Are you sure you want to clear all nodes?',
    },
    ideaCard: {
        promptLabel: 'Prompt',
        outputLabel: 'Output',
        regenerate: 'Regenerate',
        branch: 'Branch',
        delete: 'Delete',
        expand: 'Expand',
        collapse: 'Collapse',
        expandPrompt: 'Expand prompt',
        collapsePrompt: 'Collapse prompt',
        noOutput: 'Type text to save, or /ai: for AI generation',
        aiPrefix: '/ai: ',
        inputPlaceholder: 'Type to save note, or /ai: for AI...',
        aiDividerLabel: 'AI Response',
    },
    errors: {
        generic: 'Something went wrong. Please try again.',
        networkError: 'Network error. Please check your connection.',
        aiError: 'AI generation failed. Please try again.',
        quotaExceeded: 'API quota exceeded. Please try again later.',
    },
    common: {
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        retry: 'Retry',
        loading: 'Loading...',
        comingSoon: 'Coming soon!',
    },
} as const;

export type StringKeys = typeof strings;
