/**
 * String Resources - Single Source of Truth for all UI text
 * NO hardcoded strings allowed in components
 */
export const strings = {
    app: {
        name: 'ActionStation',
        tagline: 'Think visually. Connect ideas.',
    },
    auth: {
        signInWithGoogle: 'Sign in with Google',
        signOut: 'Sign out',
        signingIn: 'Signing in...',
        welcome: 'Welcome back',
    },
    workspace: {
        newWorkspace: 'New Workspace',
        untitled: 'Untitled Workspace',
        deleteConfirm: 'Are you sure you want to delete this workspace?',
    },
    canvas: {
        addNode: 'Add node',
        promptPlaceholder: 'Type a prompt (e.g. Create a LinkedIn post about discipline)',
        generating: 'Generating...',
        regenerate: 'Regenerate',
        delete: 'Delete',
        edit: 'Edit',
        generatedBy: 'Generated by Gemini',
        synthesize: 'Generate combined idea',
    },
    errors: {
        generic: 'Something went wrong. Please try again.',
        networkError: 'Network error. Please check your connection.',
        aiError: 'AI generation failed. Please try again.',
        quotaExceeded: 'API quota exceeded. Please try again later.',
    },
    common: {
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        retry: 'Retry',
        loading: 'Loading...',
    },
} as const;

export type StringKeys = typeof strings;
