export const workspaceStrings = {
    newWorkspace: 'New Workspace',
    untitled: 'Untitled Workspace',
    created: 'Workspace created',
    deleteConfirm: 'Are you sure you want to delete this workspace? This action cannot be undone.',
    deleteConfirmTitle: 'Delete Workspace',
    deleteConfirmButton: 'Delete',
    deleteDividerTitle: 'Delete Divider',
    deleteDividerMessage: 'Are you sure you want to delete this divider?',
    deleteDividerButton: 'Delete',
    deleteSuccess: 'Workspace deleted successfully',
    deleteDefaultError: 'Cannot delete the default workspace',
    addNodeTooltip: 'Add New Node',
    arrangeNodesTooltip: 'Auto Arrange (Grid)',
    freeFlowTooltip: 'Toggle Free Flowing nodes (Disables auto-grid alignment)',
    deleteWorkspaceTooltip: 'Delete Workspace',
    switching: 'Switching workspace...',
    switchError: 'Failed to switch workspace',
    offlineUnavailable: 'Offline mode unavailable',
    dragHandle: 'Drag to reorder workspace',
    reorderedSuccess: 'Workspaces reordered',
    dragCancel: 'Drag cancelled',
    nodeCount: (count: number) => `(${count})`,
};
