/**
 * Knowledge Bank String Resources
 * Extracted from main strings.ts to respect 300-line file limit
 */
export const knowledgeBankStrings = {
    title: 'Knowledge Bank',
    addButton: 'Add to Knowledge Bank',
    uploadFile: 'Upload File',
    pasteText: 'Paste Text',
    viewBank: 'View Knowledge Bank',
    saveEntry: 'Save to Knowledge Bank',
    toggleEntry: 'Toggle entry enabled',
    editEntry: 'Edit entry',
    deleteEntry: 'Delete entry',
    deleteConfirm: 'Delete?',
    toggleEnable: 'Enable',
    toggleDisable: 'Disable',
    emptyState: 'No entries yet',
    emptyStateDescription: 'Add text, images, PDFs, or Word documents to your Knowledge Bank. All AI-generated nodes will use this context automatically.',
    addFirstEntry: 'Add First Entry',
    maxEntriesReached: 'Limit reached',
    maxEntriesDescription: 'Delete an entry to add more',
    entryCount: 'entries',
    characterCount: 'characters',
    titlePlaceholder: 'Entry title',
    contentPlaceholder: 'Paste your text here...',
    processingImage: 'Processing image...',
    compressingImage: 'Compressing image...',
    describingImage: 'Describing image with AI...',
    imageDescribed: 'AI-generated description added for image',
    imageDescriptionFallback: 'Image uploaded (AI description unavailable)',
    imageDescriptionPrompt: 'Describe this image in detail for use as reference context in a knowledge base. Focus on key visual elements, text content if any, diagrams, charts, or notable features. Be concise but comprehensive.',
    processingDocx: 'Extracting text from Word document...',
    processingPdf: 'Extracting text from PDF...',
    chunkingDocument: 'Splitting large document into sections...',
    pdfExtracted: 'PDF content extracted',
    documentChunkTitle: 'Part',
    chunkBadge: 'chunk',
    summarizing: 'Generating summary...',
    summarized: 'Summary generated',
    summaryPrompt: 'Summarize the following text in 2-3 concise sentences for use as reference context in a knowledge base. Capture the key points, main ideas, and any critical details. Be factual and concise.',
    summaryLabel: 'Summary',
    tags: {
        label: 'Tags',
        placeholder: 'Add tag...',
        addTag: 'Add tag',
        removeTag: 'Remove tag',
        maxReached: 'Maximum of 5 tags reached',
        tooLong: 'Tag must be 30 characters or less',
        duplicate: 'Tag already exists',
        filterByTag: 'Filter by tag',
        clearFilter: 'Clear tag filter',
        noTags: 'No tags',
    },
    search: {
        placeholder: 'Search entries...',
        noResults: 'No matching entries',
        filterAll: 'All',
        filterText: 'Text',
        filterImage: 'Image',
        filterDocument: 'Document',
    },
    errors: {
        fileTooLarge: 'File exceeds 10MB limit',
        unsupportedType: 'Unsupported file type. Supported: TXT, MD, JSON, PNG, JPG, PDF, DOCX',
        uploadFailed: 'Failed to upload file',
        saveFailed: 'Failed to save entry',
        loadFailed: 'Failed to load Knowledge Bank',
        deleteFailed: 'Failed to delete entry',
        maxEntries: 'Maximum of 50 entries reached',
        contentTooLarge: 'Content exceeds 10,000 character limit',
        titleRequired: 'Title is required',
        pdfParseFailed: 'Failed to extract text from PDF',
        pdfEmpty: 'PDF contains no extractable text',
        docxParseFailed: 'Failed to extract text from Word document',
        docxEmpty: 'Word document contains no extractable text',
        imageDescriptionFailed: 'AI image description failed, using fallback',
        summarizationFailed: 'Summary generation failed',
    },
} as const;
